name: "Build and push artifacts to Cachix"
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: shypkgs
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix build github:srid/devour-flake -L --no-link --print-out-paths --override-input flake path:$GITHUB_WORKSPACE
    - run: nix-shell --run "echo OK"
