name: "Build and push artifacts to Cachix"
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-platforms = aarch64-linux armv6l-linux armv7-linux i386-linux i686-linux i686-windows mips-linux mips64-linux powerpc-linux powerpc64-linux riscv32-linux riscv64-linux x86_64-windows
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: shypkgs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build github:srid/devour-flake -L --no-link --print-out-paths --override-input flake path:"$GITHUB_WORKSPACE"
      - run: nix-shell -p bash --run "echo OK"
